### ISSUE TITLE
Are you missing a using directive or an assembly reference?

### ISSUE THREAD

**Issue by zORg-alex** [vexe/VFW#76]
**(Solved)
I did update to latest Unity 5.3.1f1 but for the first time I did install a version without build tools except Web Player. But then i did found out this, and that VFW do not work well with Web Player. So after final update everything started behaving. Except I still needed to add reference to CSharp-firstpass in CSharp-Editor-firstpass (if I didn't mixed things up) but this time Unity didn't reset references.
____________________________**
Hello. I feel I'm derping. But I have no idea what I did wrong during import of VFW. I did import it into Assets folder. But when I Rebuild whole solution, 924 errors show up. As I see Assembly-CSharp-firstpass is rebuilding just fine, but others do not see anything than Vexe.Runtime.Types which contains {CachedBehaviour, DelegatesExample, GOInliner, HasRequirementsAttribute, Message, Requirements, SceneTransition}. All the rest just missing.
![2015-12-30 21-22-40 assembly-csharp - vfw examples fastsave examples go gameobjecttest cs - monodevelop-unity](https://cloud.githubusercontent.com/assets/15520309/12056077/a7edd888-af3b-11e5-821a-101a6be50025.png)

**Comment by vexe** [comment]
Have you tried importing in a new project? do you still get the errors? Are the errors only in MonoDevelop or in Unity console as well? I remember trying to use MonoDevelop and started getting errors that don't really exist (not even in Unity's Console nor Visual Studio)

**Comment by zORg-alex** [comment]
Unity can't start because there are some errors. VS say's the same. I did install Unity 5.3.1f1 because of your tools (somebody claimed that it works fine with latest version). In previous version 5.1.1f1 there were different errors. I think they are fixable though. This project is quite fresh. It has a bunch of mine own... Aww... It was created in previous Unity version. I'll recreate it and try another time.

**Comment by zORg-alex** [comment]
Nope. Same thing. In new project right after import Unity Editor Said that Assets/Plugins/Vexe/Runtime/FastSave/Storage/AssetStorage.cs(87,39): error CS1501: No overload for method `GetDirectories' takes`3' arguments
Mono gives again 923 errors. Same again.
Different assemblies do not share namespaces and types.

**Comment by ajboni** [comment]
Long shot, but, are you by any chance in WebPlayer Mode?
Have you seen this #61  ?

**Comment by zORg-alex** [comment]
I've set target framework in assemblies options to 4.0. Added Assembly references. And now I do get few errors like
...Assets\Plugins\Editor\Vexe\GUIs\BaseGUI\Controls\Members.cs(33,33): Error CS0104: 'Tuple' is an ambiguous reference between 'System.Tuple<int,System.Reflection.MethodInfo>' and 'Vexe.Runtime.Types.Tuple<int,System.Reflection.MethodInfo>' (CS0104) (Assembly-CSharp-Editor-firstpass)
So I did add Vexe.Runtime.Types. to Tuples and few other fixes. And it compiled finally.
Weird. Why Assemblies are not referenced? They were previously. Or did they. Well my classes in CSharp were accessible in CSharp-Editor. But I have never used namespaces.
And yes I was in a WebPlayer also. Changed to Standalone... Nope, I have no other choice. I don't have any modules it says. I'm puzzled. Can't find any ways to get them.

What?!! When I do Open C# project from Unity it negates all my reference fixes and errors get back again. If I'm setting things back Unity ignores build and states that errors are still there.

So I figured that VFW scripts are split in 4 assemblies in a weird way. These assemblies don't have references except CSharp-Editor to CSharp. All the rest

**Comment by zORg-alex** [comment]
What?!! When I do Open C# project from Unity it negates all my reference fixes and errors get back again. If I'm setting things back Unity ignores build and states that errors are still there.
